### PR TITLE
Added python3-venv install prerequisite

### PR DESCRIPTION
**Pull request by JlnWntr**

### CODE REVIEW

**Comment by lgrahl** [comment]
Apparently, `python3 -m venv` is the way to go now.
See https://docs.python.org/3.7/library/venv.html

So, I guess we should switch to that.

**Comment by dbrgn** [comment]
If we're at it, @lgrahl, have you already tried [pipenv](https://docs.pipenv.org/)?

**Comment by dbrgn** [comment]
It's basically applying the learnings from other package managers (like Cargo and npm) to Python in order to achieve better workflows and mostly reproducible environments. It's mainly targeted at applications and brings along things like a lockfile with pinned versions and hashes.

**Comment by lgrahl** [comment]
I'm closing this due to inactivity but feel free to resubmit @JlnWntr :smiley_cat:

**Pull request closed without merging**
