### PR TITLE
Ping interval may be 0

### PR DESCRIPTION
**Pull request by dbrgn**
Or did I miss something?

I assume handling the value `0` works properly, right?

### CODE REVIEW

**Comment by lgrahl** [comment]
Now it's handled. ;)

**Comment by dbrgn** [comment]
Shouldn't the default be no ping at all?

**Comment by lgrahl** [comment]
This way we can make sure that the server cleans up dead connections. And a ping each hour shouldn't hurt.

**Comment by dbrgn** [comment]
> And a ping each hour shouldn't hurt.

I agree, but the spec says `Otherwise, ping_interval MUST be set to 0 indicating that no WebSocket ping messages SHALL be sent.`.

**Comment by lgrahl** [comment]
I thought we had this case covered but turns out I was wrong. See https://github.com/saltyrtc/saltyrtc-meta/pull/102

**Pull request merged**
