### PR TITLE
Read debug keypair configuration from env vars

### PR DESCRIPTION
**Pull request by dbrgn**
Docs how to generate the keypair and how to start the debug server would be good too.

### CODE REVIEW

**Comment by lgrahl** [comment]
I have renamed the environment variables. Any objections @dbrgn? (I am not that familiar with ENV dos and don'ts)

**Comment by dbrgn** [comment]
Sure. But if you're already renaming, what about `SALTYRTC_TLS_CERT` and `SALTYRTC_TLS_KEY`?

**Comment by dbrgn** [comment]
@lgrahl what env var names do you prefer?

**Comment by lgrahl** [comment]
Yeah, I'd be fine with these names.

**Comment by dbrgn** [comment]
Fixed and rebased.

**Pull request merged**
